// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/app-bar/search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/app-bar/search/index').default>>>>
    }
    '/api/apps/academy/course-details': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/academy/course-details.get').default>>>>
    }
    '/api/apps/academy/courses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/academy/courses.get').default>>>>
    }
    '/api/apps/calendar/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/calendar/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/calendar/[id].put').default>>>>
    }
    '/api/apps/calendar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/calendar/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/calendar/index.post').default>>>>
    }
    '/api/apps/chat/chats-and-contacts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/chat/chats-and-contacts.get').default>>>>
    }
    '/api/apps/chat/chats/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/chat/chats/[id].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/chat/chats/[id].post').default>>>>
    }
    '/api/apps/ecommerce/customers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/customers/[id].get').default>>>>
    }
    '/api/apps/ecommerce/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/customers/index.get').default>>>>
    }
    '/api/apps/ecommerce/orders/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/orders/[id].delete').default>>>>
    }
    '/api/apps/ecommerce/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/orders/index.get').default>>>>
    }
    '/api/apps/ecommerce/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/products/index.get').default>>>>
    }
    '/api/apps/ecommerce/referrals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/referrals/index.get').default>>>>
    }
    '/api/apps/ecommerce/reviews/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/reviews/[id].delete').default>>>>
    }
    '/api/apps/ecommerce/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/ecommerce/reviews/index.get').default>>>>
    }
    '/api/apps/email': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/email/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/email/index.post').default>>>>
    }
    '/api/apps/invoice/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/invoice/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/invoice/[id].get').default>>>>
    }
    '/api/apps/invoice/clients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/invoice/clients.get').default>>>>
    }
    '/api/apps/invoice': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/invoice/index.get').default>>>>
    }
    '/api/apps/logistics/vehicles': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/logistics/vehicles/index').default>>>>
    }
    '/api/apps/permissions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/permissions/index.get').default>>>>
    }
    '/api/apps/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/users/[id].get').default>>>>
    }
    '/api/apps/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/apps/users/index.post').default>>>>
    }
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/dashboard/analytics/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/analytics/projects.get').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me.get').default>>>>
    }
    '/api/pages/datatable': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/datatable.get').default>>>>
    }
    '/api/pages/faq': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/faq.get').default>>>>
    }
    '/api/pages/help-center/article': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/help-center/article/index.get').default>>>>
    }
    '/api/pages/help-center': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/help-center/index.get').default>>>>
    }
    '/api/pages/profile/header': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/profile/header.get').default>>>>
    }
    '/api/pages/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/profile/index.get').default>>>>
    }
    '/api/token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/token.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.7.4_@types+node@20.8.6_eslint@8.51.0_sass@1.69.3_stylelint@15.10.3_typescript@5.2.2/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}