/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'account-account-AddSlipFormPage': RouteRecordInfo<'account-account-AddSlipFormPage', '/account/account/AddSlipFormPage', Record<never, never>, Record<never, never>>,
    'account-account-ApprovalManagerFormPage': RouteRecordInfo<'account-account-ApprovalManagerFormPage', '/account/account/ApprovalManagerFormPage', Record<never, never>, Record<never, never>>,
    'account-account-EditSlipFormPage': RouteRecordInfo<'account-account-EditSlipFormPage', '/account/account/EditSlipFormPage', Record<never, never>, Record<never, never>>,
    'account-account-JournalFormPage': RouteRecordInfo<'account-account-JournalFormPage', '/account/account/JournalFormPage', Record<never, never>, Record<never, never>>,
    'account-account-ReceiptFormPage': RouteRecordInfo<'account-account-ReceiptFormPage', '/account/account/ReceiptFormPage', Record<never, never>, Record<never, never>>,
    'account-account-SlipFormPage': RouteRecordInfo<'account-account-SlipFormPage', '/account/account/SlipFormPage', Record<never, never>, Record<never, never>>,
    'account-assets-DepreciationSchedulePage': RouteRecordInfo<'account-assets-DepreciationSchedulePage', '/account/assets/DepreciationSchedulePage', Record<never, never>, Record<never, never>>,
    'account-assets-FixedAssetLedgerPage': RouteRecordInfo<'account-assets-FixedAssetLedgerPage', '/account/assets/FixedAssetLedgerPage', Record<never, never>, Record<never, never>>,
    'account-assets-FixedAssetRegistrationPage': RouteRecordInfo<'account-assets-FixedAssetRegistrationPage', '/account/assets/FixedAssetRegistrationPage', Record<never, never>, Record<never, never>>,
    'account-base-AccountCodeManager': RouteRecordInfo<'account-base-AccountCodeManager', '/account/base/AccountCodeManager', Record<never, never>, Record<never, never>>,
    'account-base-AccountLedgerPage': RouteRecordInfo<'account-base-AccountLedgerPage', '/account/base/AccountLedgerPage', Record<never, never>, Record<never, never>>,
    'account-base-CashJournalPage': RouteRecordInfo<'account-base-CashJournalPage', '/account/base/CashJournalPage', Record<never, never>, Record<never, never>>,
    'account-base-CustomerManagerPage': RouteRecordInfo<'account-base-CustomerManagerPage', '/account/base/CustomerManagerPage', Record<never, never>, Record<never, never>>,
    'account-base-DetailTrialBalancePage': RouteRecordInfo<'account-base-DetailTrialBalancePage', '/account/base/DetailTrialBalancePage', Record<never, never>, Record<never, never>>,
    'account-base-GeneralAccountLedgerPage': RouteRecordInfo<'account-base-GeneralAccountLedgerPage', '/account/base/GeneralAccountLedgerPage', Record<never, never>, Record<never, never>>,
    'account-budget-BudgetFormulation-TestTest': RouteRecordInfo<'account-budget-BudgetFormulation-TestTest', '/account/budget/BudgetFormulation/TestTest', Record<never, never>, Record<never, never>>,
    'account-budget-BudgetRequest-BudgetRequestPage': RouteRecordInfo<'account-budget-BudgetRequest-BudgetRequestPage', '/account/budget/BudgetRequest/BudgetRequestPage', Record<never, never>, Record<never, never>>,
    'account-budget-BudgetStatus-BudgetStatusPage': RouteRecordInfo<'account-budget-BudgetStatus-BudgetStatusPage', '/account/budget/BudgetStatus/BudgetStatusPage', Record<never, never>, Record<never, never>>,
    'account-funds-DailyFundJournalFormPage': RouteRecordInfo<'account-funds-DailyFundJournalFormPage', '/account/funds/DailyFundJournalFormPage', Record<never, never>, Record<never, never>>,
    'account-funds-DailyFundPlanInputFormPage': RouteRecordInfo<'account-funds-DailyFundPlanInputFormPage', '/account/funds/DailyFundPlanInputFormPage', Record<never, never>, Record<never, never>>,
    'account-funds-FundPlanningCalendarFormPage': RouteRecordInfo<'account-funds-FundPlanningCalendarFormPage', '/account/funds/FundPlanningCalendarFormPage', Record<never, never>, Record<never, never>>,
    'account-funds-NotePayableSpecificationFormPage': RouteRecordInfo<'account-funds-NotePayableSpecificationFormPage', '/account/funds/NotePayableSpecificationFormPage', Record<never, never>, Record<never, never>>,
    'account-funds-NoteReceivableSpecificationFormPage': RouteRecordInfo<'account-funds-NoteReceivableSpecificationFormPage', '/account/funds/NoteReceivableSpecificationFormPage', Record<never, never>, Record<never, never>>,
    'account-Home': RouteRecordInfo<'account-Home', '/account/Home', Record<never, never>, Record<never, never>>,
    'account-Home2': RouteRecordInfo<'account-Home2', '/account/Home2', Record<never, never>, Record<never, never>>,
    'account-statement-CashFlowStatementPage': RouteRecordInfo<'account-statement-CashFlowStatementPage', '/account/statement/CashFlowStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-CostStatementPage': RouteRecordInfo<'account-statement-CostStatementPage', '/account/statement/CostStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-FinancialPositionPage': RouteRecordInfo<'account-statement-FinancialPositionPage', '/account/statement/FinancialPositionPage', Record<never, never>, Record<never, never>>,
    'account-statement-IncomeStatementPage': RouteRecordInfo<'account-statement-IncomeStatementPage', '/account/statement/IncomeStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-MonthCostStatementPage': RouteRecordInfo<'account-statement-MonthCostStatementPage', '/account/statement/MonthCostStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-MonthIncomeStatementPage': RouteRecordInfo<'account-statement-MonthIncomeStatementPage', '/account/statement/MonthIncomeStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-RetainedEarningsStatementPage': RouteRecordInfo<'account-statement-RetainedEarningsStatementPage', '/account/statement/RetainedEarningsStatementPage', Record<never, never>, Record<never, never>>,
    'account-statement-TotalTrialBalancePage': RouteRecordInfo<'account-statement-TotalTrialBalancePage', '/account/statement/TotalTrialBalancePage', Record<never, never>, Record<never, never>>,
    'account-vehicle-VehicleLogbookPage': RouteRecordInfo<'account-vehicle-VehicleLogbookPage', '/account/vehicle/VehicleLogbookPage', Record<never, never>, Record<never, never>>,
    'account-vehicle-VehicleRegistrationPage': RouteRecordInfo<'account-vehicle-VehicleRegistrationPage', '/account/vehicle/VehicleRegistrationPage', Record<never, never>, Record<never, never>>,
    'apps-academy-course-details': RouteRecordInfo<'apps-academy-course-details', '/apps/academy/course-details', Record<never, never>, Record<never, never>>,
    'apps-academy-dashboard': RouteRecordInfo<'apps-academy-dashboard', '/apps/academy/dashboard', Record<never, never>, Record<never, never>>,
    'apps-academy-my-course': RouteRecordInfo<'apps-academy-my-course', '/apps/academy/my-course', Record<never, never>, Record<never, never>>,
    'apps-calendar': RouteRecordInfo<'apps-calendar', '/apps/calendar', Record<never, never>, Record<never, never>>,
    'apps-chat': RouteRecordInfo<'apps-chat', '/apps/chat', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-customer-details-id': RouteRecordInfo<'apps-ecommerce-customer-details-id', '/apps/ecommerce/customer/details/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-ecommerce-customer-list': RouteRecordInfo<'apps-ecommerce-customer-list', '/apps/ecommerce/customer/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-manage-review': RouteRecordInfo<'apps-ecommerce-manage-review', '/apps/ecommerce/manage-review', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-order-details-id': RouteRecordInfo<'apps-ecommerce-order-details-id', '/apps/ecommerce/order/details/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-ecommerce-order-list': RouteRecordInfo<'apps-ecommerce-order-list', '/apps/ecommerce/order/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-add': RouteRecordInfo<'apps-ecommerce-product-add', '/apps/ecommerce/product/add', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-category-list': RouteRecordInfo<'apps-ecommerce-product-category-list', '/apps/ecommerce/product/category-list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-product-list': RouteRecordInfo<'apps-ecommerce-product-list', '/apps/ecommerce/product/list', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-referrals': RouteRecordInfo<'apps-ecommerce-referrals', '/apps/ecommerce/referrals', Record<never, never>, Record<never, never>>,
    'apps-ecommerce-settings': RouteRecordInfo<'apps-ecommerce-settings', '/apps/ecommerce/settings', Record<never, never>, Record<never, never>>,
    'apps-email': RouteRecordInfo<'apps-email', '/apps/email', Record<never, never>, Record<never, never>>,
    'apps-invoice-add': RouteRecordInfo<'apps-invoice-add', '/apps/invoice/add', Record<never, never>, Record<never, never>>,
    'apps-invoice-edit-id': RouteRecordInfo<'apps-invoice-edit-id', '/apps/invoice/edit/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-invoice-list': RouteRecordInfo<'apps-invoice-list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'apps-invoice-preview-id': RouteRecordInfo<'apps-invoice-preview-id', '/apps/invoice/preview/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-logistics-dashboard': RouteRecordInfo<'apps-logistics-dashboard', '/apps/logistics/dashboard', Record<never, never>, Record<never, never>>,
    'apps-logistics-fleet': RouteRecordInfo<'apps-logistics-fleet', '/apps/logistics/fleet', Record<never, never>, Record<never, never>>,
    'apps-permissions': RouteRecordInfo<'apps-permissions', '/apps/permissions', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id()', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'charts-apex-chart': RouteRecordInfo<'charts-apex-chart', '/charts/apex-chart', Record<never, never>, Record<never, never>>,
    'charts-chartjs': RouteRecordInfo<'charts-chartjs', '/charts/chartjs', Record<never, never>, Record<never, never>>,
    'components-alert': RouteRecordInfo<'components-alert', '/components/alert', Record<never, never>, Record<never, never>>,
    'components-avatar': RouteRecordInfo<'components-avatar', '/components/avatar', Record<never, never>, Record<never, never>>,
    'components-badge': RouteRecordInfo<'components-badge', '/components/badge', Record<never, never>, Record<never, never>>,
    'components-button': RouteRecordInfo<'components-button', '/components/button', Record<never, never>, Record<never, never>>,
    'components-chip': RouteRecordInfo<'components-chip', '/components/chip', Record<never, never>, Record<never, never>>,
    'components-dialog': RouteRecordInfo<'components-dialog', '/components/dialog', Record<never, never>, Record<never, never>>,
    'components-expansion-panel': RouteRecordInfo<'components-expansion-panel', '/components/expansion-panel', Record<never, never>, Record<never, never>>,
    'components-list': RouteRecordInfo<'components-list', '/components/list', Record<never, never>, Record<never, never>>,
    'components-menu': RouteRecordInfo<'components-menu', '/components/menu', Record<never, never>, Record<never, never>>,
    'components-pagination': RouteRecordInfo<'components-pagination', '/components/pagination', Record<never, never>, Record<never, never>>,
    'components-progress-circular': RouteRecordInfo<'components-progress-circular', '/components/progress-circular', Record<never, never>, Record<never, never>>,
    'components-progress-linear': RouteRecordInfo<'components-progress-linear', '/components/progress-linear', Record<never, never>, Record<never, never>>,
    'components-snackbar': RouteRecordInfo<'components-snackbar', '/components/snackbar', Record<never, never>, Record<never, never>>,
    'components-tabs': RouteRecordInfo<'components-tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    'components-timeline': RouteRecordInfo<'components-timeline', '/components/timeline', Record<never, never>, Record<never, never>>,
    'components-tooltip': RouteRecordInfo<'components-tooltip', '/components/tooltip', Record<never, never>, Record<never, never>>,
    'dashboards-analytics': RouteRecordInfo<'dashboards-analytics', '/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'dashboards-crm': RouteRecordInfo<'dashboards-crm', '/dashboards/crm', Record<never, never>, Record<never, never>>,
    'dashboards-ecommerce': RouteRecordInfo<'dashboards-ecommerce', '/dashboards/ecommerce', Record<never, never>, Record<never, never>>,
    'extensions-swiper': RouteRecordInfo<'extensions-swiper', '/extensions/swiper', Record<never, never>, Record<never, never>>,
    'extensions-tour': RouteRecordInfo<'extensions-tour', '/extensions/tour', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'forms-autocomplete': RouteRecordInfo<'forms-autocomplete', '/forms/autocomplete', Record<never, never>, Record<never, never>>,
    'forms-checkbox': RouteRecordInfo<'forms-checkbox', '/forms/checkbox', Record<never, never>, Record<never, never>>,
    'forms-combobox': RouteRecordInfo<'forms-combobox', '/forms/combobox', Record<never, never>, Record<never, never>>,
    'forms-custom-input': RouteRecordInfo<'forms-custom-input', '/forms/custom-input', Record<never, never>, Record<never, never>>,
    'forms-date-time-picker': RouteRecordInfo<'forms-date-time-picker', '/forms/date-time-picker', Record<never, never>, Record<never, never>>,
    'forms-editors': RouteRecordInfo<'forms-editors', '/forms/editors', Record<never, never>, Record<never, never>>,
    'forms-file-input': RouteRecordInfo<'forms-file-input', '/forms/file-input', Record<never, never>, Record<never, never>>,
    'forms-form-layouts': RouteRecordInfo<'forms-form-layouts', '/forms/form-layouts', Record<never, never>, Record<never, never>>,
    'forms-form-validation': RouteRecordInfo<'forms-form-validation', '/forms/form-validation', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-icons': RouteRecordInfo<'forms-form-wizard-icons', '/forms/form-wizard-icons', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-numbered': RouteRecordInfo<'forms-form-wizard-numbered', '/forms/form-wizard-numbered', Record<never, never>, Record<never, never>>,
    'forms-radio': RouteRecordInfo<'forms-radio', '/forms/radio', Record<never, never>, Record<never, never>>,
    'forms-range-slider': RouteRecordInfo<'forms-range-slider', '/forms/range-slider', Record<never, never>, Record<never, never>>,
    'forms-rating': RouteRecordInfo<'forms-rating', '/forms/rating', Record<never, never>, Record<never, never>>,
    'forms-select': RouteRecordInfo<'forms-select', '/forms/select', Record<never, never>, Record<never, never>>,
    'forms-slider': RouteRecordInfo<'forms-slider', '/forms/slider', Record<never, never>, Record<never, never>>,
    'forms-switch': RouteRecordInfo<'forms-switch', '/forms/switch', Record<never, never>, Record<never, never>>,
    'forms-textarea': RouteRecordInfo<'forms-textarea', '/forms/textarea', Record<never, never>, Record<never, never>>,
    'forms-textfield': RouteRecordInfo<'forms-textfield', '/forms/textfield', Record<never, never>, Record<never, never>>,
    'front-pages-checkout': RouteRecordInfo<'front-pages-checkout', '/front-pages/checkout', Record<never, never>, Record<never, never>>,
    'front-pages-help-center': RouteRecordInfo<'front-pages-help-center', '/front-pages/help-center', Record<never, never>, Record<never, never>>,
    'front-pages-help-center-article-title': RouteRecordInfo<'front-pages-help-center-article-title', '/front-pages/help-center/article/:title()', { title: ParamValue<true> }, { title: ParamValue<false> }>,
    'front-pages-landing-page': RouteRecordInfo<'front-pages-landing-page', '/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'front-pages-payment': RouteRecordInfo<'front-pages-payment', '/front-pages/payment', Record<never, never>, Record<never, never>>,
    'front-pages-pricing': RouteRecordInfo<'front-pages-pricing', '/front-pages/pricing', Record<never, never>, Record<never, never>>,
    'hr-affair-empDetail': RouteRecordInfo<'hr-affair-empDetail', '/hr/affair/empDetail', Record<never, never>, Record<never, never>>,
    'hr-affair-empList': RouteRecordInfo<'hr-affair-empList', '/hr/affair/empList', Record<never, never>, Record<never, never>>,
    'hr-affair-registerEmpList': RouteRecordInfo<'hr-affair-registerEmpList', '/hr/affair/registerEmpList', Record<never, never>, Record<never, never>>,
    'hr-appo-log': RouteRecordInfo<'hr-appo-log', '/hr/appo/log', Record<never, never>, Record<never, never>>,
    'hr-appo-manage': RouteRecordInfo<'hr-appo-manage', '/hr/appo/manage', Record<never, never>, Record<never, never>>,
    'hr-appo-request': RouteRecordInfo<'hr-appo-request', '/hr/appo/request', Record<never, never>, Record<never, never>>,
    'hr-attendreg-daily': RouteRecordInfo<'hr-attendreg-daily', '/hr/attendreg/daily', Record<never, never>, Record<never, never>>,
    'hr-attendreg-dailyAttnd': RouteRecordInfo<'hr-attendreg-dailyAttnd', '/hr/attendreg/dailyAttnd', Record<never, never>, Record<never, never>>,
    'hr-attendreg-leave': RouteRecordInfo<'hr-attendreg-leave', '/hr/attendreg/leave', Record<never, never>, Record<never, never>>,
    'hr-attendreg-rest': RouteRecordInfo<'hr-attendreg-rest', '/hr/attendreg/rest', Record<never, never>, Record<never, never>>,
    'hr-attendreg-restAttnd': RouteRecordInfo<'hr-attendreg-restAttnd', '/hr/attendreg/restAttnd', Record<never, never>, Record<never, never>>,
    'hr-attendreg-travelAndEducationRequest': RouteRecordInfo<'hr-attendreg-travelAndEducationRequest', '/hr/attendreg/travelAndEducationRequest', Record<never, never>, Record<never, never>>,
    'hr-attndmgmt-break': RouteRecordInfo<'hr-attndmgmt-break', '/hr/attndmgmt/break', Record<never, never>, Record<never, never>>,
    'hr-attndmgmt-daily': RouteRecordInfo<'hr-attndmgmt-daily', '/hr/attndmgmt/daily', Record<never, never>, Record<never, never>>,
    'hr-attndmgmt-month': RouteRecordInfo<'hr-attndmgmt-month', '/hr/attndmgmt/month', Record<never, never>, Record<never, never>>,
    'hr-attndmgmt-rest': RouteRecordInfo<'hr-attndmgmt-rest', '/hr/attndmgmt/rest', Record<never, never>, Record<never, never>>,
    'hr-base-authManage': RouteRecordInfo<'hr-base-authManage', '/hr/base/authManage', Record<never, never>, Record<never, never>>,
    'hr-base-baseWorkTimeManage': RouteRecordInfo<'hr-base-baseWorkTimeManage', '/hr/base/baseWorkTimeManage', Record<never, never>, Record<never, never>>,
    'hr-base-codeManage': RouteRecordInfo<'hr-base-codeManage', '/hr/base/codeManage', Record<never, never>, Record<never, never>>,
    'hr-base-deptManage': RouteRecordInfo<'hr-base-deptManage', '/hr/base/deptManage', Record<never, never>, Record<never, never>>,
    'hr-base-holidayManage': RouteRecordInfo<'hr-base-holidayManage', '/hr/base/holidayManage', Record<never, never>, Record<never, never>>,
    'hr-base-positionManage': RouteRecordInfo<'hr-base-positionManage', '/hr/base/positionManage', Record<never, never>, Record<never, never>>,
    'hr-empeval-list': RouteRecordInfo<'hr-empeval-list', '/hr/empeval/list', Record<never, never>, Record<never, never>>,
    'hr-empeval-manage': RouteRecordInfo<'hr-empeval-manage', '/hr/empeval/manage', Record<never, never>, Record<never, never>>,
    'hr-Home': RouteRecordInfo<'hr-Home', '/hr/Home', Record<never, never>, Record<never, never>>,
    'hr-salbase-extManage': RouteRecordInfo<'hr-salbase-extManage', '/hr/salbase/extManage', Record<never, never>, Record<never, never>>,
    'hr-salbase-manage': RouteRecordInfo<'hr-salbase-manage', '/hr/salbase/manage', Record<never, never>, Record<never, never>>,
    'hr-salbase-socialInsure': RouteRecordInfo<'hr-salbase-socialInsure', '/hr/salbase/socialInsure', Record<never, never>, Record<never, never>>,
    'hr-salcheck-awrds': RouteRecordInfo<'hr-salcheck-awrds', '/hr/salcheck/awrds', Record<never, never>, Record<never, never>>,
    'hr-salcheck-month': RouteRecordInfo<'hr-salcheck-month', '/hr/salcheck/month', Record<never, never>, Record<never, never>>,
    'hr-salcheck-severancePay': RouteRecordInfo<'hr-salcheck-severancePay', '/hr/salcheck/severancePay', Record<never, never>, Record<never, never>>,
    'hr-salreg-award': RouteRecordInfo<'hr-salreg-award', '/hr/salreg/award', Record<never, never>, Record<never, never>>,
    'hr-salreg-month': RouteRecordInfo<'hr-salreg-month', '/hr/salreg/month', Record<never, never>, Record<never, never>>,
    'hr-salreg-mouth': RouteRecordInfo<'hr-salreg-mouth', '/hr/salreg/mouth', Record<never, never>, Record<never, never>>,
    'hr-salreg-severancePay': RouteRecordInfo<'hr-salreg-severancePay', '/hr/salreg/severancePay', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'logistic-Home': RouteRecordInfo<'logistic-Home', '/logistic/Home', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab()', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pages-authentication-forgot-password-v1': RouteRecordInfo<'pages-authentication-forgot-password-v1', '/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-forgot-password-v2': RouteRecordInfo<'pages-authentication-forgot-password-v2', '/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v2': RouteRecordInfo<'pages-authentication-login-v2', '/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-multi-steps': RouteRecordInfo<'pages-authentication-register-multi-steps', '/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v1': RouteRecordInfo<'pages-authentication-register-v1', '/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v2': RouteRecordInfo<'pages-authentication-register-v2', '/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v1': RouteRecordInfo<'pages-authentication-reset-password-v1', '/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v2': RouteRecordInfo<'pages-authentication-reset-password-v2', '/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v1': RouteRecordInfo<'pages-authentication-two-steps-v1', '/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v2': RouteRecordInfo<'pages-authentication-two-steps-v2', '/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v1': RouteRecordInfo<'pages-authentication-verify-email-v1', '/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v2': RouteRecordInfo<'pages-authentication-verify-email-v2', '/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
    'pages-cards-card-actions': RouteRecordInfo<'pages-cards-card-actions', '/pages/cards/card-actions', Record<never, never>, Record<never, never>>,
    'pages-cards-card-advance': RouteRecordInfo<'pages-cards-card-advance', '/pages/cards/card-advance', Record<never, never>, Record<never, never>>,
    'pages-cards-card-basic': RouteRecordInfo<'pages-cards-card-basic', '/pages/cards/card-basic', Record<never, never>, Record<never, never>>,
    'pages-cards-card-statistics': RouteRecordInfo<'pages-cards-card-statistics', '/pages/cards/card-statistics', Record<never, never>, Record<never, never>>,
    'pages-cards-card-widgets': RouteRecordInfo<'pages-cards-card-widgets', '/pages/cards/card-widgets', Record<never, never>, Record<never, never>>,
    'pages-dialog-examples': RouteRecordInfo<'pages-dialog-examples', '/pages/dialog-examples', Record<never, never>, Record<never, never>>,
    'pages-faq': RouteRecordInfo<'pages-faq', '/pages/faq', Record<never, never>, Record<never, never>>,
    'pages-icons': RouteRecordInfo<'pages-icons', '/pages/icons', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'pages-pricing': RouteRecordInfo<'pages-pricing', '/pages/pricing', Record<never, never>, Record<never, never>>,
    'pages-typography': RouteRecordInfo<'pages-typography', '/pages/typography', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab()', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'tables-data-table': RouteRecordInfo<'tables-data-table', '/tables/data-table', Record<never, never>, Record<never, never>>,
    'tables-simple-table': RouteRecordInfo<'tables-simple-table', '/tables/simple-table', Record<never, never>, Record<never, never>>,
    'wizard-examples-checkout': RouteRecordInfo<'wizard-examples-checkout', '/wizard-examples/checkout', Record<never, never>, Record<never, never>>,
    'wizard-examples-create-deal': RouteRecordInfo<'wizard-examples-create-deal', '/wizard-examples/create-deal', Record<never, never>, Record<never, never>>,
    'wizard-examples-property-listing': RouteRecordInfo<'wizard-examples-property-listing', '/wizard-examples/property-listing', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
