// Generated by nuxi
/// <reference types="@vueuse/nuxt" />
/// <reference types="@nuxtjs/device" />
/// <reference types="@sidebase/nuxt-auth" />
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/vue-shim.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference path="../index.d.ts" />
/// <reference types="vite/client" />
/// <reference path="types/auth.d.ts" />
/// <reference types="@pinia/nuxt" />
/// <reference path="./types/typed-router.d.ts" />
/// <reference types="vue-router/auto" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="vue-router.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="nuxt-config-schema" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
